EdForum/Areas/Admin/Controllers/CategoryController.cs
using EdForum.DataAccessLayer.Repository.IRepositoryClasses;
using EdForum.Models.Models;
using Microsoft.AspNetCore.Mvc;

namespace EdForum.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitofwork;
        public CategoryController(IUnitOfWork unitofwork)
        {
            _unitofwork = unitofwork;
        }

        #region Adding Category
        public IActionResult Index()
        {
            List<Category> objCategoryList = _unitofwork.Category.GetAllCategoryList().ToList();
            return View(objCategoryList);
        }
        [HttpGet]
        public IActionResult AddCategory()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddCategory(Category _ct)
        {
            // Adding custom validations
            if (_ct.Name == _ct.DisplayedOrder.ToString())
            {
                ModelState.AddModelError("", "Name and Displayed Order cannot be same");
            }
            if (ModelState.IsValid)
            {
                _unitofwork.Category.AddCategory(_ct);
                _unitofwork.Save();
                TempData["success"] = "Category created Successfully";
                return RedirectToAction("Index");
            }
            return View();
        }
        #endregion Add

        #region Edit
        [HttpGet]
        public IActionResult EditCategory(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category? category = _unitofwork.Category.GetCategory(x => x.Id == id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }
        [HttpPost]
        public IActionResult EditCategory(Category _category)
        {
            if (ModelState.IsValid)
            {
                _unitofwork.Category.UpdateCategory(_category);
                _unitofwork.Save();
                TempData["success"] = "Category updated successfully";
                return RedirectToAction("Index");
            }
            return View();
        }
        #endregion edit

        #region Deleting records or Removing Categories
        [HttpGet]
        public IActionResult DeleteCategory(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category? category = _unitofwork.Category.GetCategory(x => x.Id == id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }
        [HttpPost, ActionName("DeleteCategory")]
        public IActionResult DeleteCategoryPOST(int? id)
        {
            Category? category = _unitofwork.Category.GetCategory(y => y.Id == id);
            if (category == null)
            {
                return NotFound();
            }
            _unitofwork.Category.RemoveCategory(category);
            _unitofwork.Save();
            TempData["success"] = "Category deleted successfully";
            return RedirectToAction("Index");
        }

        #endregion
    }
}

EdForum/Areas/Admin/Controllers/ProductController.cs
using EdForum.DataAccessLayer.Repository.IRepositoryClasses;
using EdForum.Models.Models;
using Microsoft.AspNetCore.Mvc;

namespace EdForum.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitofwork;
        public ProductController(IUnitOfWork unitofwork)
        {
            _unitofwork = unitofwork;
        }

        #region Adding Product
        public IActionResult Index()
        {
            List<Product> objProductList = _unitofwork.Product.GetAllCategoryList().ToList();
            return View(objProductList);
        }
        [HttpGet]
        public IActionResult AddProduct()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddProduct(Product _ct)
        {
            if (ModelState.IsValid)
            {
                _unitofwork.Product.AddCategory(_ct);
                _unitofwork.Save();
                TempData["success"] = "Product created Successfully";
                return RedirectToAction("Index");
            }
            return View();
        }
        #endregion Add

        #region Edit
        [HttpGet]
        public IActionResult EditProduct(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Product? product = _unitofwork.Product.GetCategory(x => x.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }
        [HttpPost]
        public IActionResult EditProduct(Product _product)
        {
            if (ModelState.IsValid)
            {
                _unitofwork.Product.UpdateProduct(_product);
                _unitofwork.Save();
                TempData["success"] = "Product updated successfully";
                return RedirectToAction("Index");
            }
            return View();
        }
        #endregion edit

        #region Deleting records or Removing Products
        [HttpGet]
        public IActionResult DeleteProduct(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Product? product = _unitofwork.Product.GetCategory(x => x.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }
        [HttpPost, ActionName("DeleteProduct")]
        public IActionResult DeleteProductPOST(int? id)
        {
            Product? product = _unitofwork.Product.GetCategory(y => y.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            _unitofwork.Product.RemoveCategory(product);
            _unitofwork.Save();
            TempData["success"] = "Product deleted successfully";
            return RedirectToAction("Index");
        }

        #endregion
    }
}

EdForum/Areas/Customer/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using EdForum.Models;

namespace EdForum.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}
    

EdForum/Areas/Admin/Views/Category/AddCategory.cshtml
@model Category

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Create Category</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row">
            <div class="border p-3">
                @*<div asp-validation-summary="All"></div>*@
                <div class="form-floating py-2 col-12">
                    <input asp-for="Name" class="form-control border-0 shadow">
                    <label asp-for="Name" class="ms-2"></label>
                    <span class="text-danger" asp-validation-for="Name"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="DisplayedOrder" class="form-control border-0 shadow">
                    <label asp-for="DisplayedOrder" class="ms-2"></label>

                    <span class="text-danger" asp-validation-for="DisplayedOrder"></span>
                </div>
                <div class="row pt-3">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-primary form-control">Create</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Category" asp-action="Index" class="btn btn-outline-primary border form-control">Back To List</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>



@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }
}

EdForum/Areas/Admin/Views/Category/DeleteCategory.cshtml
@model Category

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Delete Category</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post">
            <input asp-for="Id" hidden />
            <div class="border p-3 mt-4">
                
                <div class="form-floating py-2 col-12">
                    <input asp-for="Name" disabled class="form-control border-0 shadow">
                    <label asp-for="Name" class="ms-2"></label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="DisplayedOrder" disabled class="form-control border-0 shadow">
                    <label asp-for="DisplayedOrder" class="ms-2"></label>
                </div>
                <div class="row mt-3">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-danger form-control">Delete</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Category" asp-action="Index" class="btn btn-outline-secondary form-control">Back To List</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

EdForum/Areas/Admin/Views/Category/EditCategory.cshtml
@model Category

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Update Category</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post">
            <input asp-for="Id" hidden />
            <div class="border p-3 mt-4">
                
                @*<div asp-validation-summary="All"></div>*@
                <div class="form-floating py-2 col-12">
                    <input asp-for="Name" class="form-control border-0 shadow">
                    <label asp-for="Name" class="ms-2"></label>
                    <span class="text-danger" asp-validation-for="Name"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="DisplayedOrder" class="form-control border-0 shadow">
                    <label asp-for="DisplayedOrder" class="ms-2"></label>
                    <span class="text-danger" asp-validation-for="DisplayedOrder"></span>
                </div>
                <div class="row mt-3">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-primary form-control">Update</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Category" asp-action="Index" class="btn btn-outline-secondary form-control">Back To List</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>




@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }
}

EdForum/Areas/Admin/Views/Category/Index.cshtml
@model List<Category>

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Category List</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pb-2">
            <div class="col-6">
                
            </div>
            <div class="col-6 text-end">
                <a asp-controller="Category" asp-action="AddCategory" class="btn btn-primary">
                    <i class="bi bi-plus-circle-fill"></i> &nbsp; Create new Category
                </a>
            </div>
        </div>
        <br />
        <table class="table table-bordered table-striped" style="width: 100%">
            <thead>
                <tr>
                    <th style="text-align:center">
                        Category Name
                    </th>
                    <th style="text-align:center">Display Order</th>
                    <th style="text-align:center">CreatedOn</th>
                    <th style="text-align:center">
                        Actions
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var i in Model.OrderBy(u => u.Id))
                {
                    <tr>
                        <td style="width: 40%">
                            @i.Name
                        </td>
                        <td style="width: 30%">
                            @i.DisplayedOrder
                        </td>
                        <td style="width: 30%">
                            @i.CreatedOn
                        </td>
                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Category" asp-action="EditCategory" asp-route-id="@i.Id" class="btn btn-primary mx-2">
                                    <i class="bi bi-pencil-square">Edit</i>
                                </a>
                                <a asp-controller="Category" asp-action="DeleteCategory" asp-route-id="@i.Id" class="btn btn-danger mx-2">
                                    <i class="bi bi-trash3-fill">Delete</i>
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

EdForum/Areas/Admin/Views/Product/AddProduct.cshtml
@model Product

<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Create Product</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row">
            <div class="border p-3">
                @*<div asp-validation-summary="All"></div>*@
                <div class="form-floating py-2 col-12">
                    <input asp-for="Title" class="form-control border-0 shadow">
                    <label asp-for="Title" class="ms-2"></label>
                    <span class="text-danger" asp-validation-for="Title"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Description" class="form-control border-0 shadow">
                    <label asp-for="Description" class="ms-2"></label>

                    <span class="text-danger" asp-validation-for="Description"></span>
                </div>

                <div class="form-floating py-2 col-12">
                    <input asp-for="ISBN" class="form-control border-0 shadow">
                    <label asp-for="ISBN" class="ms-2"></label>

                    <span class="text-danger" asp-validation-for="ISBN"></span>
                </div>

                <div class="form-floating py-2 col-12">
                    <input asp-for="Author" class="form-control border-0 shadow">
                    <label asp-for="Author" class="ms-2"></label>

                    <span class="text-danger" asp-validation-for="Author"></span>
                </div>

                <div class="form-floating py-2 col-12">
                    <input asp-for="ListPrice" class="form-control border-0 shadow">
                    <label asp-for="ListPrice" class="ms-2"></label>

                    <span class="text-danger" asp-validation-for="ListPrice"></span>
                </div>

                <div class="form-floating py-2 col-12">
                    <input asp-for="Price" class="form-control border-0 shadow">
                    <label asp-for="Price" class="ms-2"></label>

                    <span class="text-danger" asp-validation-for="Price"></span>
                </div>

                <div class="form-floating py-2 col-12">
                    <input asp-for="PricePer50" class="form-control border-0 shadow">
                    <label asp-for="PricePer50" class="ms-2"></label>

                    <span class="text-danger" asp-validation-for="PricePer50"></span>
                </div>

                <div class="form-floating py-2 col-12">
                    <input asp-for="PricePer100" class="form-control border-0 shadow">
                    <label asp-for="PricePer100" class="ms-2"></label>

                    <span class="text-danger" asp-validation-for="PricePer100"></span>
                </div>

                <div class="row pt-3">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-primary form-control">Create</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Product" asp-action="Index" class="btn btn-outline-primary border form-control">Back To List</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>



@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }
}

EdForum/Areas/Admin/Views/Product/DeleteProduct.cshtml
@model Product

<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Delete Product</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post">
            <input asp-for="Id" hidden />
            <div class="border p-3 mt-4">

                <div class="form-floating py-2 col-12">
                    <input asp-for="Title" disabled class="form-control border-0 shadow">
                    <label asp-for="Title" class="ms-2"></label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Description" disabled class="form-control border-0 shadow">
                    <label asp-for="Description" class="ms-2"></label>
                </div>

                <div class="form-floating py-2 col-12">
                    <input asp-for="ISBN" disabled class="form-control border-0 shadow">
                    <label asp-for="ISBN" class="ms-2"></label>

                </div>

                <div class="form-floating py-2 col-12">
                    <input asp-for="Author" disabled class="form-control border-0 shadow">
                    <label asp-for="Author" class="ms-2"></label>

                </div>

                <div class="form-floating py-2 col-12">
                    <input asp-for="ListPrice" disabled class="form-control border-0 shadow">
                    <label asp-for="ListPrice" class="ms-2"></label>

                </div>

                <div class="form-floating py-2 col-12">
                    <input asp-for="Price" disabled class="form-control border-0 shadow">
                    <label asp-for="Price" class="ms-2"></label>

                </div>

                <div class="form-floating py-2 col-12">
                    <input asp-for="PricePer50" disabled class="form-control border-0 shadow">
                    <label asp-for="PricePer50" class="ms-2"></label>

                </div>

                <div class="form-floating py-2 col-12">
                    <input asp-for="PricePer100" disabled class="form-control border-0 shadow">
                    <label asp-for="PricePer100" class="ms-2"></label>

                </div>

                <div class="row mt-3">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-danger form-control">Delete</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Product" asp-action="Index" class="btn btn-outline-secondary form-control">Back To List</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

EdForum/Areas/Admin/Views/Product/EditProduct.cshtml
@model Product

<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Update Product</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post">
            <input asp-for="Id" hidden />
            <div class="border p-3 mt-4">
                
                @*<div asp-validation-summary="All"></div>*@
                <div class="form-floating py-2 col-12">
                    <input asp-for="Title" class="form-control border-0 shadow">
                    <label asp-for="Title" class="ms-2"></label>
                    <span class="text-danger" asp-validation-for="Title"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <textarea asp-for="Description" class="form-control border-0 shadow"></textarea>
                    <label asp-for="Description" class="ms-2"></label>

                    <span class="text-danger" asp-validation-for="Description"></span>
                </div>

                <div class="form-floating py-2 col-12">
                    <input asp-for="ISBN" class="form-control border-0 shadow">
                    <label asp-for="ISBN" class="ms-2"></label>

                    <span class="text-danger" asp-validation-for="ISBN"></span>
                </div>

                <div class="form-floating py-2 col-12">
                    <input asp-for="Author" class="form-control border-0 shadow">
                    <label asp-for="Author" class="ms-2"></label>

                    <span class="text-danger" asp-validation-for="Author"></span>
                </div>

                <div class="form-floating py-2 col-12">
                    <input asp-for="ListPrice" class="form-control border-0 shadow">
                    <label asp-for="ListPrice" class="ms-2"></label>

                    <span class="text-danger" asp-validation-for="ListPrice"></span>
                </div>

                <div class="form-floating py-2 col-12">
                    <input asp-for="Price" class="form-control border-0 shadow">
                    <label asp-for="Price" class="ms-2"></label>

                    <span class="text-danger" asp-validation-for="Price"></span>
                </div>

                <div class="form-floating py-2 col-12">
                    <input asp-for="PricePer50" class="form-control border-0 shadow">
                    <label asp-for="PricePer50" class="ms-2"></label>

                    <span class="text-danger" asp-validation-for="PricePer50"></span>
                </div>

                <div class="form-floating py-2 col-12">
                    <input asp-for="PricePer100" class="form-control border-0 shadow">
                    <label asp-for="PricePer100" class="ms-2"></label>

                    <span class="text-danger" asp-validation-for="PricePer100"></span>
                </div>
                <div class="row mt-3">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-primary form-control">Update</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Product" asp-action="Index" class="btn btn-outline-secondary form-control">Back To List</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>




@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }
}

EdForum/Areas/Admin/Views/Product/Index.cshtml
@model List<Product>

<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Product List</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pb-2">
            <div class="col-6">
                
            </div>
            <div class="col-6 text-end">
                <a asp-controller="Product" asp-action="AddProduct" class="btn btn-primary">
                    <i class="bi bi-plus-circle-fill"></i> &nbsp; Create new Product
                </a>
            </div>
        </div>
        <br />
        <table class="table table-bordered table-striped" style="width: 100%">
            <thead>
                <tr>
                    <th style="text-align:center">Title</th>
                    <th style="text-align:center">ISBN</th>
                    <th style="text-align:center">Price</th>
                    <th style="text-align:center">Author</th>
                    <th style="text-align:center">Category</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var i in Model)
                {
                    <tr>
                        <td style="width: 40%">
                            @i.Title
                        </td>
                        <td style="width: 30%">
                            @i.ISBN
                        </td>
                        <td style="width: 30%">
                            @i.Price
                        </td>
                        <td style="width: 30%">
                            @i.Author
                        </td>
                        <td style="width: 30%">
                           
                        </td>
                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Product" asp-action="EditProduct" asp-route-id="@i.Id" class="btn btn-primary mx-2">
                                    <i class="bi bi-pencil-square">Edit</i>
                                </a>
                                <a asp-controller="Product" asp-action="DeleteProduct" asp-route-id="@i.Id" class="btn btn-danger mx-2">
                                    <i class="bi bi-trash3-fill">Delete</i>
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

EdForum/Areas/Customer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

EdForum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - EdForum</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
    <link rel="stylesheet" href="~/EdForum.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">EdForum</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link " asp-area="Customer" asp-controller="Home" asp-action="Index"><span class="visually-hidden">(current)</span>Home</a>
                    </li>
                    
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Content Management
                            </a>
                            <ul class="dropdown-menu">
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-         action="Index">Category</a>
                                </li>

                                <li class="nav-item">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp- action="Index">Product</a>
                                </li>

                                <li><hr class="dropdown-divider"></li>
                            </ul>
                        </li>
                </ul>
                <form class="d-flex">
                    <input class="form-control me-sm-2" type="search" placeholder="Search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit" fdprocessedid="5a7fkp">Search</button>
                </form>
            </div>
        </div>
    </nav>
    
</header>
<div class="container">
    <main role="main" class="pb-3">
        <partial name="_Notifications"></partial>
        @RenderBody()
    </main>
</div>

<footer class="border-top footer  bg-primary text-muted">
    <div class="container">
        Made with <i class="bi bi-bag-heart-fill"></i> by EdForum
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>